name: lint_and_test
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  push:
jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.10.8"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade pip
    - name: Install dependencies
      env:
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
      run: |
        pip install poetry
        poetry install
        poetry run python -m unidic download
    - run: poetry run ruff .
    - run: poetry run mypy src
    - run: poetry run pytest -vv
